### ISSUE TITLE
Bible: Long but not infinite list

### ISSUE THREAD

**Issue by philholden** [domenic/infinite-list-study-group#10]
I have a use case that is a bit different but may be interesting for your research group in terms of requirements.

I have Bible search engine that uses an in memory Bible. It searches onKeyDown and results appear immediately. The regex search is very fast but the DOM renders slowly and so is broken up by timers.

https://omysoul.github.io/omysoul/react-bible/
https://github.com/philholden/react-bible

I would have liked to use a virtual scroller but:

1) I would lose browser search
2) Results are not ranked by relevance but by position in the Bible. People are often more interested in the last results than the first as the New Testament is at the end of the Bible. Users know the order of books so if they scroll to the middle they would expect to be in Psalms or to the end in Revelation.

Requirements

1) Scrollbar needs to work
    * should be able to drag scrollbar from top to bottom and access verses from Genesis to Revelation.
    * using the scrollbar is akin to flipping through pages in a book (coarse)
    * using scroll wheel, trackpad is for scanning verses (fine)
    * should be seamless moving between the two (like Google maps zoom)
    * this is hard because we have to guess the size of elements that have not been rendered when jumping dragging the scrollbar.

2) Would like to be able to sync scrolling smoothly. e.g. have two panes with different Bible versions that scroll in sync. Or have two people with browsers open at different widths that scroll in sync via web sockets. This is very hard to do without virtual scrolling as it is hard to know what is in the view port without observing every element.

3) Browser in page search needs to work.

**Comment by domenic** [comment]
Hey @philholden, thanks so much for opening this, and my sincere apologies for not responding sooner!

We're consolidating this repository with https://github.com/WICG/virtual-scroller, but I have good news: I think we've got you mostly covered with the design over there. The design should accomodate all the requirements you list, I'm pretty sure. The synchronized panes is an especially interesting one, but I think the design of keeping things in the DOM will help---although we should ideally build a demo to test.

Separate from the standards work in WICG/virtual-scroller, as the Chrome team builds an implementation of the proposal behind a flag, we'd love to work more directly with you to see if what we've built could be integrated into your site. We're still early days on our implementation, but if that's OK, we'll open an issue on your react-bible repo when we have something ready for testing.

I'll close out this issue, as part of the general turndown on this repository, but will stay in touch!
