### ISSUE TITLE
maybe this can help too

### ISSUE THREAD

**Issue by 0xF48** [domenic/infinite-list-study-group#6]
maybe this can give you some creative ideas? this is an infinite scrolling tile grid that i have been working on for web based apps. tile grids can be a great choice depending on your use case.

https://github.com/arxii/preact-grid
https://arxii.github.io/preact-grid/

**Comment by domenic** [comment]
Hey @arxii, my sincere apologies for missing this issue when you posted it! We're consolidating this repository with https://github.com/WICG/virtual-scroller, and moved all studies into https://github.com/WICG/virtual-scroller/tree/master/study-group.

I'll close this issue as part of the general repository shutdown, but we'd still love a study on your preact-grid, if you'd be willing to submit it over there!
