### ISSUE TITLE
clusterize.js

### ISSUE THREAD

**Issue by bartgrantham** [domenic/infinite-list-study-group#9]
I just saw Gray Norton's talk from the Chrome conference a few days ago.

I wanted to point out [clusterize.js](https://clusterize.js.org/).  It is a framework-less script that I've had a lot of great luck with in the past week.  It was amazingly easy to adopt and makes similar design decisions as `<virtual-scroller>`.  That's it, thought you'd be interested.

**Comment by domenic** [comment]
Hey @bartgrantham, my sincere apologies for missing this issue when you posted it! We're consolidating this repository with https://github.com/WICG/virtual-scroller, and moved all studies into https://github.com/WICG/virtual-scroller/tree/master/study-group.

I'll close this issue as part of the general repository shutdown, but thanks for the pointer, and we'll definitely look into it as part of the overall research for the built-in virtual scroller!
